Repository doris-vectorized/doris-pipeline, pull requests merged in 2022-11, with the labels that each got.

#3 add pipeline session variable && make can_read lock free
  be/src/pipeline/exec/scan_operator.h
  be/src/runtime/buffer_control_block.cpp
  be/src/runtime/buffer_control_block.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/result_buffer_mgr.cpp
  be/src/runtime/result_buffer_mgr.h
  be/src/runtime/result_file_sink.cpp
  be/src/runtime/result_sink.cpp
  be/src/runtime/runtime_state.h
  be/src/util/runtime_profile.h
  be/src/vec/exec/scan/pip_scanner_context.h
  be/src/vec/exec/scan/scanner_context.cpp
  be/src/vec/exec/scan/scanner_context.h
  be/src/vec/exec/scan/vscan_node.cpp
  be/src/vec/runtime/vdata_stream_mgr.cpp
  be/src/vec/runtime/vdata_stream_recvr.cpp
  be/src/vec/runtime/vdata_stream_recvr.h
  be/src/vec/sink/vresult_file_sink.cpp
  be/src/vec/sink/vresult_sink.cpp
  be/test/runtime/result_buffer_mgr_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
Labels: area/vectorization

#2 [Exec](Pipeline) POC code Add agg operator
  be/src/exec/exec_node.cpp
  be/src/exec/exec_node.h
  be/src/pipeline/CMakeLists.txt
  be/src/pipeline/exec/agg_context.cpp
  be/src/pipeline/exec/agg_context.h
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/aggregation_sink_operator.h
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/exec/exchange_sink_operator.h
  be/src/pipeline/exec/exchange_source_operator.cpp
  be/src/pipeline/exec/final_aggregation_source_operator.cpp
  be/src/pipeline/exec/final_aggregation_source_operator.h
  be/src/pipeline/exec/operator.cpp
  be/src/pipeline/exec/operator.h
  be/src/pipeline/exec/pre_aggregation_source_operator.cpp
  be/src/pipeline/exec/pre_aggregation_source_operator.h
  be/src/pipeline/exec/scan_operator.cpp
  be/src/pipeline/pipeline.cpp
  be/src/pipeline/pipeline.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_fragment_context.h
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/vec/exec/scan/new_olap_scan_node.cpp
  be/src/vec/exec/scan/new_olap_scan_node.h
  be/src/vec/exec/vaggregation_node.cpp
  be/src/vec/exec/vaggregation_node.h
  be/src/vec/exec/vexchange_node.cpp
  be/src/vec/exec/vexchange_node.h
Labels: area/vectorization

#6 Refactor of pipeline code
  be/src/pipeline/exec/agg_context.cpp
  be/src/pipeline/exec/agg_context.h
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/exec/exchange_sink_operator.h
  be/src/pipeline/exec/exchange_source_operator.cpp
  be/src/pipeline/exec/final_aggregation_source_operator.cpp
  be/src/pipeline/exec/olap_scan_operator.cpp
  be/src/pipeline/exec/operator.cpp
  be/src/pipeline/exec/operator.h
  be/src/pipeline/exec/result_sink_operator.h
  be/src/pipeline/exec/scan_operator.cpp
  be/src/pipeline/exec/sink_buffer.cpp
  be/src/pipeline/exec/sink_buffer.h
  be/src/pipeline/pipeline.cpp
  be/src/pipeline/pipeline.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_fragment_context.h
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/pipeline/task_scheduler.cpp
  be/src/pipeline/task_scheduler.h
  be/src/vec/exec/scan/scanner_context.cpp
Labels: area/vectorization, approved, reviewed

#7 [Exec](pipeline) implementation of sort operator
  be/src/pipeline/CMakeLists.txt
  be/src/pipeline/exec/exchange_source_operator.cpp
  be/src/pipeline/exec/sort_context.h
  be/src/pipeline/exec/sort_sink_operator.cpp
  be/src/pipeline/exec/sort_sink_operator.h
  be/src/pipeline/exec/sort_source_operator.cpp
  be/src/pipeline/exec/sort_source_operator.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_task.h
  be/src/vec/exec/vsort_node.cpp
  be/src/vec/exec/vsort_node.h
Labels: area/vectorization

#11 Refactor the prepare interface and change the pipe exec task size
  be/src/common/config.h
  be/src/exec/exec_node.cpp
  be/src/exec/exec_node.h
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/exec/exchange_sink_operator.h
  be/src/pipeline/exec/exchange_source_operator.cpp
  be/src/pipeline/exec/operator.cpp
  be/src/pipeline/exec/operator.h
  be/src/pipeline/exec/sort_sink_operator.cpp
  be/src/pipeline/exec/sort_sink_operator.h
  be/src/pipeline/pipeline.cpp
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/task_scheduler.cpp
  be/src/pipeline/task_scheduler.h
  be/src/runtime/exec_env_init.cpp
  be/src/vec/exec/vsort_node.cpp
  be/src/vec/exec/vsort_node.h
  be/src/vec/sink/vresult_sink.cpp
Labels: area/vectorization

#15 [Refactor](pipeline) remove useless dynamic_cast and const_cast
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/aggregation_sink_operator.h
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/exec/exchange_sink_operator.h
  be/src/pipeline/exec/exchange_source_operator.cpp
  be/src/pipeline/exec/exchange_source_operator.h
  be/src/pipeline/exec/final_aggregation_source_operator.cpp
  be/src/pipeline/exec/final_aggregation_source_operator.h
  be/src/pipeline/exec/olap_scan_operator.cpp
  be/src/pipeline/exec/olap_scan_operator.h
  be/src/pipeline/exec/operator.cpp
  be/src/pipeline/exec/operator.h
  be/src/pipeline/exec/pre_aggregation_source_operator.cpp
  be/src/pipeline/exec/result_sink_operator.h
  be/src/pipeline/exec/scan_operator.cpp
  be/src/pipeline/exec/scan_operator.h
  be/src/pipeline/exec/sort_sink_operator.cpp
  be/src/pipeline/exec/sort_sink_operator.h
  be/src/pipeline/exec/sort_source_operator.cpp
  be/src/pipeline/exec/sort_source_operator.h
  be/src/pipeline/pipeline_fragment_context.cpp
Labels: approved, reviewed

#16 refactor of exchange sink
  be/src/exec/data_sink.cpp
  be/src/exec/data_sink.h
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/exec/exchange_sink_operator.h
  be/src/pipeline/exec/operator.h
  be/src/pipeline/exec/sink_buffer.cpp
  be/src/pipeline/exec/sink_buffer.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/runtime/plan_fragment_executor.cpp
  be/src/vec/exec/vexchange_node.cpp
  be/src/vec/runtime/vdata_stream_recvr.cpp
  be/src/vec/runtime/vdata_stream_recvr.h
  be/src/vec/runtime/vsorted_run_merger.cpp
  be/src/vec/sink/vdata_stream_sender.cpp
  be/src/vec/sink/vdata_stream_sender.h
  be/src/vec/sink/vjdbc_table_sink.cpp
  be/src/vec/sink/vjdbc_table_sink.h
  be/src/vec/sink/vmysql_table_sink.cpp
  be/src/vec/sink/vmysql_table_sink.h
  be/src/vec/sink/vodbc_table_sink.cpp
  be/src/vec/sink/vodbc_table_sink.h
  be/src/vec/sink/vresult_file_sink.cpp
  be/src/vec/sink/vresult_file_sink.h
  be/src/vec/sink/vresult_sink.cpp
  be/src/vec/sink/vresult_sink.h
  be/src/vec/sink/vtable_sink.cpp
  be/src/vec/sink/vtable_sink.h
  be/src/vec/sink/vtablet_sink.cpp
  be/src/vec/sink/vtablet_sink.h
  be/test/vec/runtime/vdata_stream_test.cpp
Labels: area/vectorization

#17 Refactor the code of Agg Source Opeartor / Sink Operator
  be/src/pipeline/CMakeLists.txt
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/aggregation_sink_operator.h
  be/src/pipeline/exec/aggregation_source_operator.cpp
  be/src/pipeline/exec/aggregation_source_operator.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/vec/exec/vaggregation_node.cpp
  be/src/vec/exec/vaggregation_node.h
Labels: area/vectorization

#19 [Refactor](pipeline) change OperatorTemplate to OperatorBuilder
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/aggregation_sink_operator.h
  be/src/pipeline/exec/aggregation_source_operator.cpp
  be/src/pipeline/exec/aggregation_source_operator.h
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/exec/exchange_sink_operator.h
  be/src/pipeline/exec/exchange_source_operator.cpp
  be/src/pipeline/exec/exchange_source_operator.h
  be/src/pipeline/exec/olap_scan_operator.cpp
  be/src/pipeline/exec/olap_scan_operator.h
  be/src/pipeline/exec/operator.cpp
  be/src/pipeline/exec/operator.h
  be/src/pipeline/exec/pre_aggregation_source_operator.cpp
  be/src/pipeline/exec/pre_aggregation_source_operator.h
  be/src/pipeline/exec/result_sink_operator.cpp
  be/src/pipeline/exec/result_sink_operator.h
  be/src/pipeline/exec/scan_operator.cpp
  be/src/pipeline/exec/scan_operator.h
  be/src/pipeline/exec/sort_sink_operator.cpp
  be/src/pipeline/exec/sort_sink_operator.h
  be/src/pipeline/exec/sort_source_operator.cpp
  be/src/pipeline/exec/sort_source_operator.h
  be/src/pipeline/pipeline.cpp
  be/src/pipeline/pipeline.h
  be/src/pipeline/pipeline_fragment_context.cpp
Labels: approved, reviewed

#20 [Pipeline](exchange) refactor of sink buffer
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/exec/exchange_source_operator.cpp
  be/src/pipeline/exec/exchange_source_operator.h
  be/src/pipeline/exec/olap_scan_operator.cpp
  be/src/pipeline/exec/olap_scan_operator.h
  be/src/pipeline/exec/sink_buffer.cpp
  be/src/pipeline/exec/sink_buffer.h
  be/src/util/proto_util.h
  be/src/vec/runtime/vdata_stream_recvr.h
  be/src/vec/sink/vdata_stream_sender.cpp
  be/src/vec/sink/vdata_stream_sender.h
Labels: area/vectorization

#25 [Refactor] (Pipeline) refactor the stream agg code
  be/src/exec/exec_node.h
  be/src/pipeline/CMakeLists.txt
  be/src/pipeline/exec/agg_context.cpp
  be/src/pipeline/exec/agg_context.h
  be/src/pipeline/exec/aggregation_source_operator.cpp
  be/src/pipeline/exec/pre_aggregation_sink_operator.cpp
  be/src/pipeline/exec/pre_aggregation_source_operator.cpp
  be/src/pipeline/exec/streaming_aggregation_sink_operator.cpp
  be/src/pipeline/exec/streaming_aggregation_sink_operator.h
  be/src/pipeline/exec/streaming_aggregation_source_operator.cpp
  be/src/pipeline/exec/streaming_aggregation_source_operator.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/vec/exec/vaggregation_node.cpp
  be/src/vec/exec/vaggregation_node.h
Labels: area/vectorization, approved, reviewed

#23 [Pipeline](memtracker) add memtracker for pipeline query
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/exec/exchange_source_operator.cpp
  be/src/pipeline/exec/pre_aggregation_sink_operator.cpp
  be/src/pipeline/exec/pre_aggregation_source_operator.cpp
  be/src/pipeline/exec/result_sink_operator.cpp
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/runtime/fragment_mgr.cpp
Labels: area/vectorization, reviewed
